version: '3.8'
services:
  api:
    container_name: node_assignment
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  frontend:
    container_name: frontend
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
 data: {}